### ISSUE TITLE
[Bug] Doesn't Play Iron Door sounds

### ISSUE THREAD

**Issue by RyanCR03** [boafur/HarderZombies#1]
iron doors have their own hit sounds `minecraft:entity.zombie.attack_iron_door` but they instead use `minecraft:entity.zombie.attack_wooden_door`

**Comment by boafur** [comment]
Thanks for bringing this to my attention. I guess I thought that since zombies could never break iron doors, it would be illogical for there to be a sound for it. I am curious as to why it still exists, however.
This should be fixed in the next commit.
